### ISSUE TITLE
Boundary checking on GUI

### ISSUE THREAD

**Issue by ooee123** [ooee123/ForestFriends#6]

**Comment by imlisayip** [comment]
The words are currently not printing out of the expected canvas

**Comment by imlisayip** [comment]
Found a lead:

Canvas width - xcoord width - textWidth

If that is negative, the words are out of bounds:
In this case, js will inject a warning

**Comment by imlisayip** [comment]
Now use JS. if the width is bigger, dont save the file and alert the user

**Comment by imlisayip** [comment]
One inch border is created on the canvas, and letters will be red if it extends past its board size
